repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: '(_pb2.py|_pb2_grpc.py)$'
      - id: end-of-file-fixer
        exclude: '(_pb2.py|_pb2_grpc.py)$'
      - id: check-yaml
      - id: debug-statements
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ['--max-line-length=140', '--extend-ignore=E203,W503,BLK100']
        additional_dependencies: [flake8-black]
        exclude: '(_pb2.py|_pb2_grpc.py)$'

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        files: '.*\.pyi?$'
        exclude: '.*_pb2\.pyi?$'
