[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mydlgo"
version = "0.1.0"
description = "My code implementation for the Deep Learning and The Game of Go book."
authors = [
    { name = "Paco" }
]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "pillow>=10.4.0",
    "pytest>=8.3.2",
    "pytest-cov>=5.0.0",
    "numpy>=1.9.0",
    "keras-core>=0.1.7",
    "torch>=2.4.0",
    "torchvision>=0.19.0",
    "psutil>=6.0.0",
    "types-six>=1.16.21.20240513",
    "mypy>=1.11.2",
    "six>=1.17.0",
    "tqdm>=4.67.1",
]

[project.optional-dependencies]
dev = [
    "pre-commit>=3.8.0",
]
docs = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.5.34",
]

[project.scripts]
app = "dlgo.dlgo:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["dlgo*", "scripts*", "misc*"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --import-mode=importlib"
testpaths = ["tests"]

[tool.mypy]
ignore_missing_imports = true
namespace_packages = true
explicit_package_bases = true
mypy_path = "src"

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = [
    "E", "F", "I", "B", "C4", "UP", "N", "ANN", "S", "A", "COM", "C90", "D",
    "T10", "EM", "EXE", "ISC", "G", "INP", "PIE", "T20", "PYI", "PT", "Q",
    "RSE", "RET", "SLF", "SIM", "TID", "TCH", "ARG", "PTH", "ERA", "PD",
    "PGH", "PL", "TRY"
]
ignore = [
    "D100", "D104", "D211","D212", "ANN101", "ANN102", "ANN401", "S101",
    "PT018", "INP001", "ANN001", "ANN201", "ANN202", "ANN204", "D102",
    "ERA001", "D101", "COM812", "ISC001","E501","F405","N802","N806",
    "T201","G004","C901","PLR0913", "PLR0912","PLR0915","PLR0911",
    "TRY300","UP038","S603"
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.uv.sources]
torch = [
  { index = "pytorch-cu124", marker = "sys_platform == 'linux'" },
  { index = "pytorch-cpu", marker = "sys_platform == 'darwin'" }
]
torchvision = [
  { index = "pytorch-cu124", marker = "sys_platform == 'linux'" },
  { index = "pytorch-cpu", marker = "sys_platform == 'darwin'" }
]


[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
